### ISSUE TITLE
Where/How to include atlas (TractSeg)

### ISSUE THREAD

**Issue by smeisler** [MASILab/Pandora-WhiteMatterAtlas#1]
Hello Pandora team,

Thank you for releasing this atlas! I am using [Tractoflow](https://tractoflow-documentation.readthedocs.io/en/latest/pipeline/launch.html) and [TractSeg](https://github.com/MIC-DKFZ/TractSeg/tree/master/tractseg/data) to process and segment my DTI images, respectively. It isn't clear to me where and how to introduce the atlas. I see in the preprint in the "Usage Notes" section: 

> "The investigator may choose to register their image to the MNI template, and can either warp their data to template space or apply the inverse transform to get white matter labels into the subject native space"

I know TractSeg is distributed with an MNI 152 FA template that is used to warp subject images to MNI space and that the inverse of the transformation matrix can be used to warp back to native space. I do not understand the warp to the template space, since it isn't a single scalar image like the FA template is, and when this would take place relative to the TractSeg pipeline.

Please let me know if you have any further guidance about usage.

Thanks,
Steven

**Comment by BennettLandman** [comment]
I am closing the older bug reports as these were missed. We are now better tracking reports across the organization. Please re-open if this continues to be a blocker.
